# Generated by jeweler
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ciridiri}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vasily Polovnyov"]
  s.date = %q{2010-10-01}
  s.description = %q{Dead simple wiki engine}
  s.email = %q{vasily@polovnyov.ru}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "config.ru",
     "lib/ciridiri.rb",
     "lib/ciridiri/extensions.rb",
     "lib/ciridiri/finders.rb",
     "lib/ciridiri/page.rb",
     "lib/ciridiri/paths.rb",
     "public/css/base.css",
     "public/css/print.css",
     "public/js/application.js",
     "test/ciridiri_test.rb",
     "test/page_test.rb",
     "test/test_helper.rb",
     "views/edit.erb",
     "views/layout.erb",
     "views/show.erb"
  ]
  s.homepage = %q{http://vast.github.com/ciridiri.rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dead simple wiki engine}
  s.test_files = [
    "test/test_helper.rb",
     "test/ciridiri_test.rb",
     "test/page_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.1"])
      s.add_development_dependency(%q<rack-test>, [">= 0.3.0"])
      s.add_development_dependency(%q<contest>, [">= 0.1.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.1"])
      s.add_dependency(%q<rack-test>, [">= 0.3.0"])
      s.add_dependency(%q<contest>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.1"])
    s.add_dependency(%q<rack-test>, [">= 0.3.0"])
    s.add_dependency(%q<contest>, [">= 0.1.0"])
  end
end

